_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_background_style: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity_reference_revisions: 0
  faqfield: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  geofield: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_tabs: 0
  jquery_ui_touch_punch: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  leaflet: 0
  leaflet_markercluster: 0
  leaflet_views: 0
  link: 0
  live_clock: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  openweather: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  quicktabs: 0
  quicktabs_accordion: 0
  quicktabs_jqueryui: 0
  rdf: 0
  scrollup: 0
  search: 0
  shortcut: 0
  sitemap: 0
  sitewide_alert: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  smtp: 0
  social_media_links: 0
  social_media_links_field: 0
  superfish: 0
  system: 0
  tablefield: 0
  taxi: 0
  taxonomy: 0
  telephone: 0
  telephone_advanced: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_accordion: 0
  views_fieldsets: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_example_composite: 0
  webform_example_element: 0
  webform_example_element_properties: 0
  webform_example_handler: 0
  webform_example_remote_post: 0
  webform_example_variant: 0
  webform_examples: 0
  webform_examples_accessibility: 0
  webform_icheck: 0
  webform_image_select: 0
  webform_location_geocomplete: 0
  webform_node: 0
  webform_options_custom: 0
  webform_options_limit: 0
  webform_scheduled_email: 0
  webform_share: 0
  webform_shortcuts: 0
  webform_submission_export_import: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_toggles: 0
  webform_ui: 0
  pathauto: 1
  webform_bootstrap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  empty_page: 1000
  standard: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  classy: 0
  bootstrap5: 0
  bahrain: 0
  claro: 0
profile: standard
