scrollup_position: 1
scrollup_button_bg_color: '#CCCCCC'
scrollup_button_hover_bg_color: '#000000'
scrollup_title: 'Scroll up'
scrollup_window_position: '600'
scrollup_speed: '0'
scrollup_themename:
  - bahrain
