_core:
  default_config_hash: xu0yG13sSQJcXrOJJqsn44W_hUWAIFHVlphrzxT2ycU
page_title: Sitemap
message:
  value: ''
  format: plain_text
plugins:
  'menu:main-menu':
    enabled: true
    weight: -37
    settings:
      title: 'Main Menu'
      show_disabled: true
    id: 'menu:main-menu'
    provider: sitemap
  'menu:footer':
    enabled: true
    weight: -35
    settings:
      title: Footer
      show_disabled: false
    id: 'menu:footer'
    provider: sitemap
  frontpage:
    enabled: false
include_css: false
