_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 50a9692b-4b67-4780-9720-9731b2e84bbc
name: 'Bahrain Airport'
mail: admin@example.com
slogan: ''
page:
  403: /node/22
  404: /node/18
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
