_core:
  default_config_hash: t7clj3mzmOGrXX0HuCH5usf0vEqRtnMTBFVBIEmZ5pc
first_day: 6
country:
  default: BH
timezone:
  default: Asia/Bahrain
  user:
    configurable: true
    default: 0
    warn: false
