label: 'صالات وفندق'
description: 'صالات وفندق'
display:
  default:
    display_options:
      fields:
        view_node:
          text: 'عرض المزيد'
      header:
        area:
          content:
            value: "<h2>صالات وفندق</h2>\r\n<p>هل تحتاج إلى استراحة قبل أو بعد رحلة طويلة؟ تراجع إلى إحدى صالات المغادرة أو الوصول الحصرية أو فندق مطار البحرين للاسترخاء أو العمل أو الاستمتاع بمجموعة مختارة من الأطعمة والمشروبات</p>\r\n"
            format: basic_html
