label: 'معارض الفنون، المعارض الفنية'
display:
  default:
    display_options:
      fields:
        view_node:
          text: 'عرض المزيد'
      header:
        area:
          content:
            value: "<h2>معارض الفنون، المعارض الفنية</h2>\r\n<p>مع مجموعة واسعة من الأعمال الفنية المحلية والتحف الثقافية المعروضة بفخر في مطار البحرين الدولي ، يمكن للمسافرين الآن تجربة التراث الفني للمملكة دون الحاجة إلى وضع أقدامهم خارج المبنى. تضم المحطة أعمال الفنانين البحرينيين الموهوبين ، في الماضي والحاضر ، وهي عبارة عن منصة ثقافية تحتفل بالطابع المتميز للمملكة.</p>\r\n"
            format: basic_html
      filters:
        tid:
          expose:
            description: ''
  galleries_page:
    display_title: صفحة
